# ForecastEx

## Web REST API

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import requests, json, os
from pprint import pprint

## Get live markets

In [3]:
from get_live_markets import get_live_markets
markets = get_live_markets()

In [35]:
from add_category_to_markets import add_category_to_markets
df_markets = add_category_to_markets(markets)

In [36]:
df_markets = df_markets[['category', 'name', 'symbol', 'conid']].sort_values(by=['category', 'name'])

In [37]:
conid_to_market = {market['conid']: market for market in markets}

In [38]:
df_markets.head(3)

    category                                 name symbol      conid
126  Climate  Annual Global Temperature Threshold   GTTA  776339242
82   Climate           Atmospheric Carbon Dioxide    ACD  712856705
84   Climate      Global Carbon Dioxide Emissions    GCE  732764729

## Get forecastex markets excluding financials

In [11]:
from fetch_all_contracts import fetch_all_contracts
from tqdm.auto import tqdm

In [12]:
for market in tqdm(markets):
    if 'contracts' not in market:
        market['contracts'] = fetch_all_contracts(market['conid'])
        print(market['conid'], len(market['contracts']))

  0%|          | 0/206 [00:00<?, ?it/s]

796056051 10
658663572 0
791099755 30
766914439 8
712856730 0
745923947 0
752108858 0
766914639 4
788713854 44
788713829 0
788713839 0
796079989 0
796079999 0
796080005 0
796080015 0
796080020 0
796080045 0
798491013 30
798491023 30
796080030 6
796080039 10
793085633 0
793085658 0
793085673 0
793085682 0
793085688 0
786030226 0
786030232 0
786030241 0
786554238 0
786554271 0
786554284 0
771326556 4
766914564 4
767906110 8
766914574 6
766914581 2
800591677 30
725452870 0
733131966 4
745923952 4
796056057 2
800591710 16
573031117 0
582530257 0
626425574 0
751047555 0
771326535 8
791099721 0
791099730 0
791099793 0
791099803 0
791099770 0
791099776 0
791099786 0
791099827 0
791099833 0
802185942 0
802185948 0
767906100 4
767906124 2
626425591 0
658663567 0
712856689 0
712856715 0
726203920 0
771326527 2
745923962 12
745923968 12
745923978 4
725452876 0
726203945 0
766914502 4
800320229 0
726203939 0
798087648 30
766914423 4
766914429 6
799576107 0
768815597 4
771326565 10
766914591 4
712856705 0
732764723 0
732764729 0
752108843 0
780951151 0
780951156 40
767906118 10
725452900 0
773080465 0
773080475 0
727520270 0
732764737 0
751047545 0
791099715 0
791099736 0
791099745 0
791099760 0
791099810 0
791099816 0
793085619 0
793085625 0
793085643 0
793085648 0
793085667 0
793085699 0
794909229 0
794909244 0
794909252 0
794909286 0
794909292 0
794909303 0
794909319 0
794909325 0
783245080 0
796603945 20
800320239 0
800591695 0
796603915 0
800591719 0
771326550 8
782087991 4
712856720 0
752108848 0
752108866 0
776339242 0
776339249 0
766914644 4
766914654 8
758853990 2
766914508 6
766914519 4
766914469 10
766914532 12
767284956 8
771326590 4
781673006 0
782368645 0
766914615 6
787272475 0
766914494 14
766914542 10
773080482 0
781672996 0
725452893 0
732764706 0
732764712 0
767906135 10
658663557 0
712856699 0
751047539 0
758853983 0
712856682 0
726203930 0
727520252 0
727520260 0
786554165 0
786554175 0
786554183 0
786554189 0
786554198 0
786554204 0
786554213 0
786554223 0
786554228 0
786554244 0
786554254 0
786554261 0
786554278 0
797020963 0
725452887 0
751047561 0
794909223 0
794909269 0
794909279 0
794909309 0
797020954 0
800591685 0
800591700 0
766914598 10
766914604 8
766914549 8
766914559 8
723432940 0
723432951 0
723434353 0
727981253 0
727981263 0
766914621 2
766914629 2
766914406 10
766914412 8
766914445 6
766914525 16
626425612 0
783895015 0
796603954 30
796603930 12
796603939 12
11004968 0
14721310 0
11004958 0
24771018 0
796603920 18
782575029 0

In [13]:
forecastex = [market for market in markets if len(market['contracts']) > 0]

In [14]:
len(markets), len(forecastex)

(206, 65)

## Get current probability for each market contract

In [15]:
from get_candidate_probability import get_candidate_probability

In [16]:
from tqdm.auto import tqdm

In [17]:
for market in tqdm(forecastex):
    for contract in market['contracts']:
        conid = contract['conid']
        if 'probability' not in contract:
            try:
                contract['probability'] = get_candidate_probability(conid)
            except:
                contract['probability'] = None
                print('error', contract['shortDescription'])
        try:
            print(conid, contract['shortDescription'], contract['probability']['probability_pct'])
        except:
            pass

  0%|          | 0/65 [00:00<?, ?it/s]

796056496 MNYCG Nov04'25 Sliwa YES @FORECASTX 6.0
796056501 MNYCG Nov04'25 Sliwa NO @FORECASTX 95.0
796056506 MNYCG Nov04'25 Cuomo YES @FORECASTX 16.0
796056511 MNYCG Nov04'25 Cuomo NO @FORECASTX 85.0
796056520 MNYCG Nov04'25 Mamdani YES @FORECASTX 71.0
796056525 MNYCG Nov04'25 Mamdani NO @FORECASTX 30.0
796056531 MNYCG Nov04'25 Adams YES @FORECASTX 9.0
796056534 MNYCG Nov04'25 Adams NO @FORECASTX 92.0
791103640 FFDEC Jul30'25 Lower25bps YES @FORECASTX 9.0
791103645 FFDEC Jul30'25 Lower25bps NO @FORECASTX 92.0
791103649 FFDEC Jul30'25 Nochange YES @FORECASTX 88.5
791103652 FFDEC Jul30'25 Nochange NO @FORECASTX 12.5
791103682 FFDEC Sep17'25 Lower25bps YES @FORECASTX 59.0
791103687 FFDEC Sep17'25 Lower25bps NO @FORECASTX 42.0
791103688 FFDEC Sep17'25 Nochange YES @FORECASTX 45.0
791103693 FFDEC Sep17'25 Nochange NO @FORECASTX 56.00000000000001
791103699 FFDEC Sep17'25 Raise50bpsormore YES @FORECASTX 11.0
791103702 FFDEC Sep17'25 Raise50bpsormore NO @FORECASTX 90.0
791103705 FFDEC Sep17'25 Lower50bpsormore YES @FORECASTX 15.0
791103708 FFDEC Sep17'25 Lower50bpsormore NO @FORECASTX 86.0
793089188 FFDEC Oct29'25 Nochange YES @FORECASTX 41.0
793089195 FFDEC Oct29'25 Nochange NO @FORECASTX 60.0
793089205 FFDEC Oct29'25 Lower25bps YES @FORECASTX 48.0
793089210 FFDEC Oct29'25 Lower25bps NO @FORECASTX 53.0
788715372 USTRF Sep30'25 Russia YES @FORECASTX 45.0
788715378 USTRF Sep30'25 Russia NO @FORECASTX 56.00000000000001
788715383 USTRF Sep30'25 Automobiles YES @FORECASTX 30.0
788715384 USTRF Sep30'25 Automobiles NO @FORECASTX 71.0
788715389 USTRF Sep30'25 EuropeanUnion YES @FORECASTX 32.0
788715394 USTRF Sep30'25 EuropeanUnion NO @FORECASTX 69.0
788715405 USTRF Sep30'25 Semiconductors YES @FORECASTX 37.0
788715411 USTRF Sep30'25 Semiconductors NO @FORECASTX 64.0
788715420 USTRF Sep30'25 Smartphones YES @FORECASTX 38.0
788715424 USTRF Sep30'25 Smartphones NO @FORECASTX 63.0
788715429 USTRF Dec31'25 China YES @FORECASTX 52.0
788715434 USTRF Dec31'25 China NO @FORECASTX 49.0
788715492 USTRF Dec31'25 Semiconductors YES @FORECASTX 59.0
788715499 USTRF Dec31'25 Semiconductors NO @FORECASTX 42.0
error SKDEC Oct23'25 Lower25bps YES @FORECASTX
error SKDEC Nov27'25 Raise50bpsormore YES @FORECASTX
796082793 SDPNC Mar03'26 Cooper YES @FORECASTX 88.0
796082796 SDPNC Mar03'26 Cooper NO @FORECASTX 13.0
796083048 SRPNC Mar03'26 Trump YES @FORECASTX 11.799999999999999
796083053 SRPNC Mar03'26 Trump NO @FORECASTX 89.3
771327516 MSEAD Aug05'25 Harrell YES @FORECASTX 61.0
771327520 MSEAD Aug05'25 Harrell NO @FORECASTX 40.0
767285535 GPNMD Jun02'26 Haaland YES @FORECASTX 71.0
767285539 GPNMD Jun02'26 Haaland NO @FORECASTX 30.0
762089343 HORC Nov'26 Democratic YES @FORECASTX 69.0
762089344 HORC Nov'26 Democratic NO @FORECASTX 32.0
773659700 HORC Nov'26 Republican YES @FORECASTX 31.0
error HORC Nov'26 Republican NO @FORECASTX
773659815 SENM Nov'26 Democratic YES @FORECASTX 27.0
773659816 SENM Nov'26 Democratic NO @FORECASTX 74.0
771327413 MMSPG Nov04'25 Frey YES @FORECASTX 51.0
771327418 MMSPG Nov04'25 Frey NO @FORECASTX 50.0
771327431 MMSPG Nov04'25 Fateh YES @FORECASTX 40.0
771327432 MMSPG Nov04'25 Fateh NO @FORECASTX 61.0
767906308 GRVA Nov04'25 Earle-Sears YES @FORECASTX 9.0
767906315 GRVA Nov04'25 Earle-Sears NO @FORECASTX 92.0
745924025 PCD Aug'28 Newsome YES @FORECASTX 25.0
745924028 PCD Aug'28 Newsome NO @FORECASTX 76.0
745924067 PCD Aug'28 Ocasio-Cortez YES @FORECASTX 12.0
745924070 PCD Aug'28 Ocasio-Cortez NO @FORECASTX 89.0
745924112 PCR Aug'28 Vance YES @FORECASTX 56.99999999999999
745924117 PCR Aug'28 Vance NO @FORECASTX 44.0
745924146 PCR Aug'28 Desantis YES @FORECASTX 5.0
745924151 PCR Aug'28 Desantis NO @FORECASTX 96.0
745924152 PCR Aug'28 Youngkin YES @FORECASTX 5.0
745924157 PCR Aug'28 Youngkin NO @FORECASTX 96.0
772771675 PCR Aug'28 Trump YES @FORECASTX 6.0
772771678 PCR Aug'28 Trump NO @FORECASTX 95.0
767285685 GPPAR May19'26 Garrity YES @FORECASTX 62.0
767285690 GPPAR May19'26 Garrity NO @FORECASTX 39.0
798087668 CADEC Jul30'25 Raise25bps YES @FORECASTX 25.0
798087675 CADEC Jul30'25 Raise25bps NO @FORECASTX 76.0
767285565 GPNYD Jun23'26 Hochul YES @FORECASTX 71.0
767285568 GPNYD Jun23'26 Hochul NO @FORECASTX 30.0
767285583 GPNYR Jun23'26 Lawler YES @FORECASTX 7.000000000000001
767285585 GPNYR Jun23'26 Lawler NO @FORECASTX 94.0
768816023 GRNJ Nov04'25 Sherrill YES @FORECASTX 84.0
768816024 GRNJ Nov04'25 Sherrill NO @FORECASTX 17.0
768816029 GRNJ Nov04'25 Ciattarelli YES @FORECASTX 16.0
768816033 GRNJ Nov04'25 Ciattarelli NO @FORECASTX 85.0
error MDETN Aug05'25 Craig NO @FORECASTX
771327350 MDETN Aug05'25 Kinloch YES @FORECASTX 11.0
error MDETN Aug05'25 Kinloch NO @FORECASTX
771327366 MDETN Aug05'25 Sheffield YES @FORECASTX 80.0
771327369 MDETN Aug05'25 Sheffield NO @FORECASTX 21.0
780951286 HLF Dec'25 Florida YES @FORECASTX 39.0
780951289 HLF Dec'25 Florida NO @FORECASTX 62.0
782090868 SRPTX Mar03'26 Paxton YES @FORECASTX 60.0
782090875 SRPTX Mar03'26 Paxton NO @FORECASTX 41.0
767285628 GPOHR May05'26 Yost YES @FORECASTX 5.0
767285635 GPOHR May05'26 Yost NO @FORECASTX 96.0
error GPCOD Jun30'26 Crow NO @FORECASTX
767285117 GPFLR Aug18'26 Donalds YES @FORECASTX 73.0
767285122 GPFLR Aug18'26 Donalds NO @FORECASTX 28.000000000000004
767285157 GPFLR Aug18'26 DeSantis YES @FORECASTX 18.0
767285162 GPFLR Aug18'26 DeSantis NO @FORECASTX 83.0
771327316 MBOSG Nov04'25 Wu YES @FORECASTX 89.0
771327323 MBOSG Nov04'25 Wu NO @FORECASTX 12.0
771327326 MBOSG Nov04'25 Kraft YES @FORECASTX 11.0
771327330 MBOSG Nov04'25 Kraft NO @FORECASTX 90.0
767285263 GPKSD Aug04'26 Holscher YES @FORECASTX 39.0
767285265 GPKSD Aug04'26 Holscher NO @FORECASTX 62.0
767285268 GPKSD Aug04'26 Corson YES @FORECASTX 36.0
767285275 GPKSD Aug04'26 Corson NO @FORECASTX 65.0
767285287 GPKSD Aug04'26 Toland YES @FORECASTX 6.0
767285288 GPKSD Aug04'26 Toland NO @FORECASTX 95.0
error GPGAD May19'26 Bottoms YES @FORECASTX
error GPGAD May19'26 Dickens YES @FORECASTX
767285012 GPCAD Jun02'26 Kounalakis YES @FORECASTX 9.5
767285019 GPCAD Jun02'26 Kounalakis NO @FORECASTX 91.5
767285031 GPCAD Jun02'26 Yee YES @FORECASTX 4.0
767285032 GPCAD Jun02'26 Yee NO @FORECASTX 97.0
767285037 GPCAD Jun02'26 Harris YES @FORECASTX 31.5
767285043 GPCAD Jun02'26 Harris NO @FORECASTX 69.5

In [18]:
f2 = [x.copy() for x in forecastex]

In [19]:
for market in f2:
    market['contracts'] = [x for x in market['contracts'] if x['probability']]

In [20]:
f2 = [market for market in f2 if market['contracts']]

In [21]:
len(f2), len(forecastex)

(26, 65)

## Open Interest (must run chrome in debug mode)

https://www.perplexity.ai/search/how-do-i-do-this-request-in-py-LKWOZo0lRNegn9r7ALA1dw

google-chrome   --remote-debugging-port=9222   --user-data-dir="$HOME/.chrome-debug-test"   https://forecasttrader.interactivebrokers.com/eventtrader/ &
curl http://localhost:9222/json

In [22]:
from OI_to_integer import OI_to_integer

In [24]:
from run_get_OI import run_get_OI

In [ ]:
for market in tqdm(f2):
    for contract in tqdm(market['contracts']):
        if 'OI' not in contract:
            conid = contract['conid']
            OI = await run_get_OI([conid])
            OI = list(OI.values())[0]
            contract['OI'] = OI_to_integer(OI)

In [33]:
contract

{'market': 'California',
 'popularityRank': 1032271,
 'name': "GPCAD Jun02'26 Harris",
 'longDescription': 'Will Kamala Harris win the California Democratic primary for governor in 2026?',
 'putOrCall': 'P',
 'expiration': '20260717',
 'currency': 'USD',
 'lastTradeMillis': 1784332740000,
 'lastTradeDate': '20260717',
 'lastTradeTime': '1859',
 'timezone': 'America/Chicago',
 'commodityCode': 'GPCAD',
 'eventAuthorityURL': 'https://www.sos.ca.gov/elections',
 'eventFixedPayout': '1',
 'sourceAgency': 'California Secretary of State Elections Division',
 'marketRulesLink': 'https://data.forecastex.com/regulatory/GPTermsandConditions.pdf',
 'underlyingName': 'California Governor Democratic Primary',
 'categories': ['g17493', 'g17467', 'g7428'],
 'expectedResolutionTime': '20260717185959',
 'expectedPayoutTime': '20260718130000',
 'timespecifierParam': '2026.6.2',
 'exchange': 'FORECASTX',
 'priceIncrement': 0.01,
 'tradingHours': {'timezone': 'America/Chicago', 'holidays': []},
 'conid': 767285043,
 'underlyingConid': 766914525,
 'underlyingSymbol': 'GPCAD',
 'shortDescription': "GPCAD Jun02'26 Harris NO @FORECASTX",
 'strike': 5.0,
 'strikeLabel': 'Harris',
 'probability': {'conid': 767285043,
  'probability_pct': 69.5,
  'timestamp': '2025-07-25T20:30:00Z',
  'timestamps': 1753475400,
  'prices': [0.695],
  'volume': [230.0]},
 'OI': 140.0}

## Collect and filter

In [ ]:
rows = []
for market in f2:
    for ctx in market['contracts']:
        contract = ctx.copy()
        probability = contract['probability']
        contract['probability_pct'] = probability['probability_pct']
        contract['weekly_volume'] = sum(probability['volume'])
        contract['yesNo'] = 'YES' if contract['putOrCall'] == 'C' else 'NO'
        for x in ['putOrCall','popularityRank', 'expiration', 'lastTradeMillis', 'lastTradeTime','eventFixedPayout', 'commodityCode', 'strike', 'market',
                    'categories', 'expectedResolutionTime', 'expectedPayoutTime', 'timespecifierParam', 'sourceAgency', 'marketRulesLink', 
                    'exchange', 'priceIncrement', 'currency', 'timezone', 'eventAuthorityURL', 'probability', 'tradingHours']:
            del contract[x]
        rows.append(contract)

In [39]:
from add_category_to_markets import add_category_to_markets
df = add_category_to_markets(rows, 'longDescription')

In [40]:
df = df[['category','underlyingName', 'longDescription', 'shortDescription', 'strikeLabel', 'yesNo', 'probability_pct',  'OI', 'lastTradeDate', 'conid']].sort_values(by=['category', 'underlyingName', 'strikeLabel', 'yesNo']).reset_index(drop=True)
df1 = df[(df.probability_pct > 25 ) & (df.probability_pct < 75 ) & (df.yesNo == 'YES')].reset_index(drop=True)

In [41]:
df1

,category,underlyingName,longDescription,shortDescription,strikeLabel,yesNo,probability_pct,OI,lastTradeDate,conid
0,Election,California Governor Democratic Primary,Will Kamala Harris win the California Democratic primary for governor in 2026?,GPCAD Jun02'26 Harris YES @FORECASTX,Harris,YES,31.5,140.0,20260717,767285037
1,Election,Florida Governor Republican Primary,Will Byron Donalds win the Florida Republican primary for governor in 2026?,GPFLR Aug18'26 Donalds YES @FORECASTX,Donalds,YES,73.0,288.0,20260903,767285117
2,Election,General Election for New York City Mayor,Will Zohran Mamdani win the New York City general election for mayor in 2025?,MNYCG Nov04'25 Mamdani YES @FORECASTX,Mamdani,YES,71.0,1190000.0,20251129,796056520
3,Election,Kansas Governor Democratic Primary,Will Ethan Corson win the Kansas Democratic primary for governor in 2026?,GPKSD Aug04'26 Corson YES @FORECASTX,Corson,YES,36.0,250.0,20260911,767285268
4,Election,Kansas Governor Democratic Primary,Will Julie Holscher win the Kansas Democratic primary for governor in 2026?,GPKSD Aug04'26 Holscher YES @FORECASTX,Holscher,YES,39.0,290.0,20260911,767285263
5,Election,Mayoral Democratic Primary in Seattle,Will Bruce Harrell win the Seattle Democratic Primary election for Mayor in 2025?,MSEAD Aug05'25 Harrell YES @FORECASTX,Harrell,YES,61.0,1680.0,20250819,771327516
6,Election,Mayoral General Election in Minneapolis,Will Omar Fateh win the Minneapolis general election for Mayor in 2025?,MMSPG Nov04'25 Fateh YES @FORECASTX,Fateh,YES,40.0,304.0,20251114,771327431
7,Election,Mayoral General Election in Minneapolis,Will Jacob Frey win the Minneapolis general election for Mayor in 2025?,MMSPG Nov04'25 Frey YES @FORECASTX,Frey,YES,51.0,170.0,20251114,771327413
8,Election,New Mexico Governor Democratic Primary,Will Deb Haaland win the New Mexico Democratic primary for governor in 2026?,GPNMD Jun02'26 Haaland YES @FORECASTX,Haaland,YES,71.0,405.0,20260630,767285535
9,Election,New York Governor Democratic Primary,Will Kathy Hochul win the New York Democratic primary for governor in 2026?,GPNYD Jun23'26 Hochul YES @FORECASTX,Hochul,YES,71.0,124.0,20260730,767285565
10,Election,Pennsylvania Governor Republican Primary,Will Stacy Garrity win the Pennsylvania Republican primary for governor in 2026?,GPPAR May19'26 Garrity YES @FORECASTX,Garrity,YES,62.0,215.0,20260626,767285685
11,Election,Texas Republican US Senate Primary,Will Ken Paxton win the Texas Republican US Senate Primary in 2025?,SRPTX Mar03'26 Paxton YES @FORECASTX,Paxton,YES,60.0,285.0,20260303,782090868
12,Election,US House of Representatives Control,Will the Democratic Party win a majority in the United States House of Representatives in the 2026 general election?,HORC Nov'26 Democratic YES @FORECASTX,Democratic,YES,69.0,122000.0,20270102,762089343
13,Election,US House of Representatives Control,Will the Republican Party win a majority in the United States House of Representatives in the 2026 general election?,HORC Nov'26 Republican YES @FORECASTX,Republican,YES,31.0,62000.0,20270102,773659700
14,Election,US Presidential Candidate Republican,Will JD Vance win the Republican Nomination for US President in 2028?,PCR Aug'28 Vance YES @FORECASTX,Vance,YES,57.0,5520.0,20280831,745924112
15,Election,US Senate Majority,Will the Democratic Party win a US Senate Majority in the 2026 general election?,SENM Nov'26 Democratic YES @FORECASTX,Democratic,YES,27.0,4290.0,20270102,773659815
16,Macro,Fed Decision,"Will the Fed lower the rate 25 bps at the September 17, 2025 meeting?",FFDEC Sep17'25 Lower25bps YES @FORECASTX,Lower 25bps,YES,59.0,450.0,20250917,791103682
17,Macro,Fed Decision,"Will the Fed lower the rate 25 bps at the October 29, 2025 meeting?",FFDEC Oct29'25 Lower25bps YES @FORECASTX,Lower 25bps,YES,48.0,60.0,20251029,793089205
18,Macro,Fed Decision,"Will the Fed leave the rate unchanged at the September 17, 2025 meeting?",FFDEC Sep17'25 Nochange YES @FORECASTX,No change,YES,45.0,481.0,20250917,791103688
19,Macro,Fed Decision,"Will the Fed leave the rate unchanged at the October 29, 2025 meeting?",FFDEC Oct29'25 Nochange YES @FORECASTX,No change,YES,41.0,321.0,20251029,793089188
20,Macro,Hurricane Landfall,Will there be a major hurricane landfall within 50 miles of Florida in 2025?,HLF Dec'25 Florida YES @FORECASTX,Florida,YES,39.0,43.0,20251231,780951286
21,Macro,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Automobiles and Auto Parts by September 30, 2025?",USTRF Sep30'25 Automobiles YES @FORECASTX,Automobiles,YES,30.0,10.0,20251001,788715383
22,Macro,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on China by December 31, 2025?",USTRF Dec31'25 China YES @FORECASTX,China,YES,52.0,20.0,20260101,788715429
23,Macro,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on the European Union by September 30, 2025?",USTRF Sep30'25 EuropeanUnion YES @FORECASTX,EuropeanUnion,YES,32.0,20.0,20251001,788715389
24,Macro,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Russia by September 30, 2025?",USTRF Sep30'25 Russia YES @FORECASTX,Russia,YES,45.0,30.0,20251001,788715372
25,Macro,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Semiconductors by September 30, 2025?",USTRF Sep30'25 Semiconductors YES @FORECASTX,Semiconductors,YES,37.0,70.0,20251001,788715405
26,Macro,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Semiconductors by December 31, 2025?",USTRF Dec31'25 Semiconductors YES @FORECASTX,Semiconductors,YES,59.0,280.0,20260101,788715492
27,Macro,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Smartphones by September 30, 2025?",USTRF Sep30'25 Smartphones YES @FORECASTX,Smartphones,YES,38.0,20.0,20251001,788715420

In [42]:
df1.to_csv('forecastex.csv')

In [43]:
df2 = df1.sort_values(by=['underlyingName', 'strikeLabel'])
df2 = df2[['underlyingName', 'longDescription', 'shortDescription', 'strikeLabel', 'yesNo', 'probability_pct', 'OI', 'lastTradeDate', 'conid']]
df2 = df2[df2.lastTradeDate <= '20251028']
df2.sort_values(by='lastTradeDate')

,underlyingName,longDescription,shortDescription,strikeLabel,yesNo,probability_pct,OI,lastTradeDate,conid
5,Mayoral Democratic Primary in Seattle,Will Bruce Harrell win the Seattle Democratic Primary election for Mayor in 2025?,MSEAD Aug05'25 Harrell YES @FORECASTX,Harrell,YES,61.0,1680.0,20250819,771327516
16,Fed Decision,"Will the Fed lower the rate 25 bps at the September 17, 2025 meeting?",FFDEC Sep17'25 Lower25bps YES @FORECASTX,Lower 25bps,YES,59.0,450.0,20250917,791103682
18,Fed Decision,"Will the Fed leave the rate unchanged at the September 17, 2025 meeting?",FFDEC Sep17'25 Nochange YES @FORECASTX,No change,YES,45.0,481.0,20250917,791103688
21,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Automobiles and Auto Parts by September 30, 2025?",USTRF Sep30'25 Automobiles YES @FORECASTX,Automobiles,YES,30.0,10.0,20251001,788715383
23,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on the European Union by September 30, 2025?",USTRF Sep30'25 EuropeanUnion YES @FORECASTX,EuropeanUnion,YES,32.0,20.0,20251001,788715389
24,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Russia by September 30, 2025?",USTRF Sep30'25 Russia YES @FORECASTX,Russia,YES,45.0,30.0,20251001,788715372
25,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Semiconductors by September 30, 2025?",USTRF Sep30'25 Semiconductors YES @FORECASTX,Semiconductors,YES,37.0,70.0,20251001,788715405
27,US Tariffs Enacted via Executive Order,"Will the United States impose additional tariffs on Smartphones by September 30, 2025?",USTRF Sep30'25 Smartphones YES @FORECASTX,Smartphones,YES,38.0,20.0,20251001,788715420

In [44]:
from datetime import datetime

In [46]:
from make_glimt_question import make_glimt_question

In [47]:
ifps = df2.apply(make_glimt_question, axis=1)

In [48]:
len(ifps)

8

In [49]:
from save_ifps_to_disk import save_ifps_to_disk
id_to_ifp = save_ifps_to_disk(ifps)

In [50]:
from gather_news_for_ifps import gather_news_for_ifps
news = gather_news_for_ifps(ifps)

saved glimt/news/791103682.txt
saved glimt/news/791103688.txt
saved glimt/news/771327516.txt
saved glimt/news/788715383.txt
saved glimt/news/788715389.txt
saved glimt/news/788715372.txt
saved glimt/news/788715405.txt
saved glimt/news/788715420.txt

In [227]:
from detailed_proposition import detailed_proposition
from wiki_semantic_search import wiki_semantic_search
from split_news_into_text_and_urls import split_news_into_text_and_urls
from create_source_summaries import create_source_summaries
from rephrase_binary_outcomes import rephrase_binary_outcomes
from format_research import format_research
from glimt_forecast_prompt import glimt_forecast_prompt
from humor_me import humor_me
from get_forecast_components import *
from median_forecast import median_forecast
from median_rationale import median_rationale
from datetime import datetime

loading massive wiki index 2025-07-24 21:51:33.210260
loading wiki article titles 2025-07-24 21:52:41.002267
loading sentence transformer model 2025-07-24 21:52:44.181085
done 2025-07-24 21:52:49.595186

In [ ]:
for ifp in ifps[1:]:
    print('begin FORECASTING', ifp['id'], ifp['props']['title'], datetime.now())
    title_plus_criteria = detailed_proposition(ifp)
    wiki_articles = wiki_semantic_search(title_plus_criteria)
    ifp_news_sources, ifp_news_text = split_news_into_text_and_urls(ifp, news)
    source_summaries, sources = create_source_summaries(ifp['id'], title_plus_criteria, wiki_articles, ifp_news_sources, ifp_news_text)
    rephrase_binary_outcomes(ifp)
    research = format_research(source_summaries)
    prompt, rejected = glimt_forecast_prompt(ifp, research)
    ## Run the prompt 5 times
    prompt_tries = 2 # Waste of time on Mistral 4 bit
    answers = [humor_me(prompt, i+1) for i in range(prompt_tries)]
    binProbs = [get_bin_probs(a) for a in answers]
    rights = [get_rights(a) for a in answers]
    wrongs = [get_wrongs(a) for a in answers]
    ## Median forecasts and rationales
    forecast = rejected + median_forecast(binProbs)
    right = median_rationale(rights)
    wrong = median_rationale(wrongs)
    result = (forecast, right, wrong, sources)
    fn = f'glimt/forecast'
    import os
    os.makedirs(fn, exist_ok=True)
    fn = f"{fn}/{ifp['id']}.json"
    import json
    with open(fn, 'w') as f:
        json.dump(result, f)

In [253]:
ifp

{'id': 788715420,
 'type': 'bins',
 'state': 'active',
 'dates': {'startDay': '20250724', 'endDay': '20251001'},
 'props': {'title': 'Will the United States impose additional tariffs on Smartphones by September 30, 2025?',
  'shortTitle': "USTRF Sep30'25 Smartphones YES @FORECASTX",
  'details': ''},
 'kind': 'discrete',
 'bins': [{'props': {'title': 'The United States will impose additional tariffs on smartphones by September 30, 2025.',
    'ai_title': '',
    'order': 0,
    'color': ''},
   'isActive': True,
   'endDay': 0},
  {'props': {'title': 'The United States will not impose additional tariffs on smartphones by September 30, 2025.',
    'ai_title': '',
    'order': 0,
    'color': ''},
   'isActive': True,
   'endDay': 0}]}

In [262]:
contracts = df.to_dict(orient='records')

In [266]:
contracts = {contract['conid']: contract for contract in contracts}

In [ ]:
for ifp in ifps:
    fn = f'glimt/forecast'
    fn = f"{fn}/{ifp['id']}.json"
    with open(fn, 'r') as f:
        forecast = json.load(f)
    [[Pyes, Pno], Rfor, Ragainst, sources] = forecast
    contract = contracts[ifp['id']]
    yesNo = contract['yesNo']
    pct = contract['probability_pct']
    yesPct = pct if yesNo == 'YES' else 100-pct
    noPct = 100-pct if yesNo == 'YES' else pct
    report = f"""
{ifp['props']['title']}
{ifp['props']['shortTitle']}

YES {100*Pyes} bot / {yesPct} crowd
NO  {100*Pno} bot  / {noPct} crowd

Reasons for YES
===============
{Rfor}

Reasosn for NO
==============
{Ragainst}

----------------------------------------"""
    print(report)